// Authentication packages:
// - @farcaster/quick-auth: Verifies JWT tokens from MiniApp Quick Auth
// - @farcaster/auth-client: Verifies SIWF signatures from web Auth Kit
import { createClient, Errors } from '@farcaster/quick-auth';
import { createAppClient, viemConnector } from '@farcaster/auth-client';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Env = any;

export class AuthService {
  private kv: any;
  private client: ReturnType<typeof createClient>;
  private appClient: ReturnType<typeof createAppClient>;
  private hostname: string;

  constructor(kv: any, hostname: string) {
    this.kv = kv;
    this.client = createClient();
    this.appClient = createAppClient({
      relay: 'https://relay.farcaster.xyz',
      ethereum: viemConnector({
        rpcUrl: 'https://mainnet.optimism.io',
      }),
    });
    this.hostname = hostname;
  }

  static fromEnv(env: Env, requestUrl?: string): AuthService {
    // Prefer actual hostname from request, fall back to config
    let hostname = env.HOSTNAME || 'localhost:5173';
    
    // If request URL provided, use it for preview URLs
    if (requestUrl) {
      try {
        const url = new URL(requestUrl);
        // Use request hostname for workers.dev domains (handles preview URLs)
        if (url.hostname.includes('.workers.dev')) {
          hostname = url.hostname;
        }
      } catch {
        // Fall back to configured hostname
      }
    }
    
    console.log('[AUTH] AuthService initialized with hostname:', hostname);
    console.log('[AUTH] Request URL:', requestUrl);
    console.log('[AUTH] Env HOSTNAME:', env.HOSTNAME);
    
    return new AuthService(env.KV_USER_PROFILES, hostname);
  }

  async generateNonce(): Promise<string> {
    const nonce = crypto.randomUUID();
    console.log('[AUTH] Generated nonce:', nonce.substring(0, 8) + '...', '(expires in 5 min)');
    // Store nonce with 5 minute expiration
    await this.kv.put(`nonce:${nonce}`, 'true', { expirationTtl: 300 });
    console.log('[AUTH] Nonce stored in KV with key:', `nonce:${nonce.substring(0, 8)}...`);
    return nonce;
  }

  async verifyNonce(nonce: string): Promise<boolean> {
    console.log('[AUTH] Verifying nonce:', nonce.substring(0, 8) + '...');
    const exists = await this.kv.get(`nonce:${nonce}`);
    console.log('[AUTH] Nonce exists in KV:', !!exists);
    if (exists) {
      // Invalidate nonce after use to prevent replay attacks
      await this.kv.delete(`nonce:${nonce}`);
      console.log('[AUTH] ✅ Nonce verified and consumed');
      return true;
    }
    console.log('[AUTH] ❌ Nonce not found or expired');
    return false;
  }

  /**
   * Verify a Sign In With Farcaster (SIWF) message and signature
   * @param message The SIWF message signed by the user
   * @param signature The signature from the user
   * @param nonce The nonce that was used in the message
   * @returns Object with success flag, fid, and optional error message
   */
  async verifySIWFMessage(params: {
    message: string;
    signature: string;
    nonce: string;
  }): Promise<{ success: boolean; fid?: number; error?: string }> {
    try {
      console.log('[AUTH] 🔐 Verifying SIWF message');
      console.log('[AUTH] Nonce from message:', params.nonce.substring(0, 8) + '...');
      console.log('[AUTH] Domain configured for verification:', this.hostname);
      console.log('[AUTH] Full message:', params.message);
      console.log('[AUTH] Signature:', params.signature.substring(0, 20) + '...');
      
      // Parse the message to extract the domain that was actually signed
      const messageLines = params.message.split('\n');
      const uriLine = messageLines.find(line => line.startsWith('URI:'));
      const domainLine = messageLines.find(line => line.includes('wants you to sign in with your Ethereum account'));
      console.log('[AUTH] URI from message:', uriLine);
      console.log('[AUTH] Domain line from message:', domainLine);
      
      // Verify the signature using @farcaster/auth-client
      // The nonce is generated by auth-kit/relay and included in the SIWE message
      // We verify the signature is valid for this message (which includes the nonce)
      const result = await this.appClient.verifySignInMessage({
        nonce: params.nonce,
        domain: this.hostname,
        message: params.message,
        signature: params.signature as `0x${string}`,
        acceptAuthAddress: true, // Accept auth addresses in addition to custody addresses
      });

      if (!result.success) {
        console.log('[AUTH] ❌ Signature verification failed');
        console.log('[AUTH] Result details:', JSON.stringify(result));
        return { success: false, error: 'Invalid signature' };
      }

      console.log('[AUTH] ✅ SIWF verification complete! FID:', result.fid);
      return {
        success: true,
        fid: result.fid,
      };
    } catch (e) {
      console.error('[AUTH] ❌ Error verifying SIWF message:', e);
      console.error('[AUTH] Error details:', e instanceof Error ? e.message : String(e));
      console.error('[AUTH] Error stack:', e instanceof Error ? e.stack : 'No stack trace');
      return { success: false, error: 'Verification failed' };
    }
  }

  /**
   * Verify a Quick Auth JWT token
   * @param token The JWT token from the Authorization header
   * @returns Object with valid flag and fid if valid
   */
  async verifyQuickAuthToken(token: string): Promise<{ valid: boolean; fid?: number; error?: string }> {
    try {
      const payload = await this.client.verifyJwt({
        token,
        domain: this.hostname,
      });

      // The payload.sub contains the FID
      return { valid: true, fid: payload.sub };
    } catch (e) {
      // For preview URLs, try wildcard matching on workers.dev domains
      if (this.hostname.includes('.workers.dev') && e instanceof Error && e.message?.includes('domain')) {
        try {
          // Extract base domain pattern (e.g., "qbase-v2.z00.workers.dev" from "abc123.qbase-v2-dev.z00.workers.dev")
          const baseDomain = this.hostname.split('.').slice(-3).join('.');
          const payload = await this.client.verifyJwt({
            token,
            domain: baseDomain,
          });
          return { valid: true, fid: payload.sub };
        } catch {
          // Fall through to original error handling
        }
      }
      if (e instanceof Errors.InvalidTokenError) {
        // Don't log JWS errors - they're expected for session tokens
        // The middleware will try session token verification next
        return { valid: false, error: 'Invalid token' };
      }

      // Only log unexpected errors (not JWS errors which are normal for web users)
      const errorMessage = e instanceof Error ? e.message : String(e);
      if (!errorMessage.includes('JWS') && !errorMessage.includes('JWE')) {
        console.error('Error verifying Quick Auth token:', e);
      }
      return { valid: false, error: 'Token verification failed' };
    }
  }

  /**
   * Middleware helper to extract and verify Bearer token from Authorization header
   */
  async verifyAuthHeader(authHeader: string | null): Promise<{ valid: boolean; fid?: number; error?: string }> {
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return { valid: false, error: 'Missing or invalid Authorization header' };
    }

    const token = authHeader.split(' ')[1];
    return this.verifyQuickAuthToken(token);
  }
}
