// @ts-nocheck
/**
 * TopicService
 * 
 * Service for managing topics - CRUD operations, search, and associations with queries.
 * Topics are automatically generated by AI during question creation and stored for discovery.
 */

import type { Topic, TopicWithMetrics, TopicListOptions, TopicListResult } from '../../src/lib/types';

export class TopicService {
  /**
   * Get or create topics from names
   * Used during question creation when AI generates topic names
   * 
   * @param db - D1 database instance
   * @param topicNames - Array of topic names to get or create
   * @returns Array of Topic objects
   */
  static async getOrCreateTopics(
    db: any,
    topicNames: string[]
  ): Promise<Topic[]> {
    const topics: Topic[] = [];
    const now = Date.now();
    
    for (const name of topicNames) {
      // Normalize topic name (lowercase, trim)
      const normalizedName = name.trim().toLowerCase();
      
      if (!normalizedName) continue;
      
      // Try to find existing topic (case-insensitive)
      const existing = await db.prepare(`
        SELECT * FROM Topics 
        WHERE LOWER(name) = LOWER(?)
      `).bind(normalizedName).first();
      
      if (existing) {
        topics.push(existing as Topic);
      } else {
        // Create new topic
        const result = await db.prepare(`
          INSERT INTO Topics (name, created_at)
          VALUES (?, ?)
          RETURNING *
        `).bind(normalizedName, now).first();
        
        if (result) {
          topics.push(result as Topic);
          
          // Initialize metrics for new topic
          await db.prepare(`
            INSERT INTO topic_metrics (topic_id, last_updated)
            VALUES (?, ?)
          `).bind(result.id, now).run();
        }
      }
    }
    
    return topics;
  }
  
  /**
   * Associate topics with a query
   * Creates entries in QueryTopics junction table
   * 
   * @param db - D1 database instance
   * @param queryId - Query UUID
   * @param topicIds - Array of topic IDs to associate
   */
  static async associateTopicsWithQuery(
    db: any,
    queryId: string,
    topicIds: number[]
  ): Promise<void> {
    for (const topicId of topicIds) {
      await db.prepare(`
        INSERT OR IGNORE INTO QueryTopics (query_id, topic_id)
        VALUES (?, ?)
      `).bind(queryId, topicId).run();
    }
  }
  
  /**
   * Get topics for a query
   * 
   * @param db - D1 database instance
   * @param queryId - Query UUID
   * @returns Array of Topic objects
   */
  static async getQueryTopics(
    db: any,
    queryId: string
  ): Promise<Topic[]> {
    const { results } = await db.prepare(`
      SELECT t.* 
      FROM Topics t
      INNER JOIN QueryTopics qt ON t.id = qt.topic_id
      WHERE qt.query_id = ?
      ORDER BY t.name
    `).bind(queryId).all();
    
    return results as Topic[];
  }
  
  /**
   * Search topics by name (autocomplete)
   * 
   * @param db - D1 database instance
   * @param query - Search query string
   * @param limit - Maximum number of results
   * @returns Array of matching topics
   */
  static async searchTopics(
    db: any,
    query: string,
    limit: number = 10
  ): Promise<Topic[]> {
    const searchTerm = `%${query.trim().toLowerCase()}%`;
    
    const { results } = await db.prepare(`
      SELECT * FROM Topics
      WHERE LOWER(name) LIKE ?
      ORDER BY name
      LIMIT ?
    `).bind(searchTerm, limit).all();
    
    return results as Topic[];
  }
  
  /**
   * Get topic with metrics
   * 
   * @param db - D1 database instance
   * @param topicId - Topic ID or name
   * @returns Topic with metrics or null
   */
  static async getTopicWithMetrics(
    db: any,
    topicIdOrName: number | string
  ): Promise<TopicWithMetrics | null> {
    let query: string;
    let bindValue: number | string;
    
    if (typeof topicIdOrName === 'number') {
      query = `
        SELECT t.*, tm.*
        FROM Topics t
        LEFT JOIN topic_metrics tm ON t.id = tm.topic_id
        WHERE t.id = ?
      `;
      bindValue = topicIdOrName;
    } else {
      query = `
        SELECT t.*, tm.*
        FROM Topics t
        LEFT JOIN topic_metrics tm ON t.id = tm.topic_id
        WHERE LOWER(t.name) = LOWER(?)
      `;
      bindValue = topicIdOrName;
    }
    
    const result = await db.prepare(query).bind(bindValue).first();
    
    return result as TopicWithMetrics | null;
  }
  
  /**
   * List topics with pagination and sorting
   * 
   * @param db - D1 database instance
   * @param options - Listing options (limit, offset, sort, filter)
   * @returns Paginated list of topics with metrics
   */
  static async listTopics(
    db: any,
    options: TopicListOptions = {}
  ): Promise<TopicListResult> {
    const {
      limit = 50,
      offset = 0,
      sortBy = 'momentum',
      timeWindow = '7d'
    } = options;
    
    // Build ORDER BY clause
    let orderBy: string;
    switch (sortBy) {
      case 'momentum':
        orderBy = 'tm.momentum_score DESC';
        break;
      case 'recent':
        orderBy = 't.created_at DESC';
        break;
      case 'popular':
        orderBy = 'tm.total_questions DESC';
        break;
      case 'alphabetical':
        orderBy = 't.name ASC';
        break;
      default:
        orderBy = 'tm.momentum_score DESC';
    }
    
    // Get total count
    const countResult = await db.prepare(`
      SELECT COUNT(*) as total FROM Topics
    `).first();
    
    const total = countResult?.total || 0;
    
    // Get topics with metrics
    const { results } = await db.prepare(`
      SELECT t.*, tm.*
      FROM Topics t
      LEFT JOIN topic_metrics tm ON t.id = tm.topic_id
      ORDER BY ${orderBy}
      LIMIT ? OFFSET ?
    `).bind(limit, offset).all();
    
    return {
      topics: results as TopicWithMetrics[],
      total,
      limit,
      offset
    };
  }
  
  /**
   * Get related topics (topics that co-occur frequently)
   * 
   * @param db - D1 database instance
   * @param topicId - Topic ID
   * @param limit - Maximum number of results
   * @returns Array of related topics with metrics
   */
  static async getRelatedTopics(
    db: any,
    topicId: number,
    limit: number = 5
  ): Promise<TopicWithMetrics[]> {
    const { results } = await db.prepare(`
      SELECT t.*, tm.*, tr.co_occurrence_count
      FROM topic_relations tr
      INNER JOIN Topics t ON (
        CASE 
          WHEN tr.topic_id_1 = ? THEN t.id = tr.topic_id_2
          ELSE t.id = tr.topic_id_1
        END
      )
      LEFT JOIN topic_metrics tm ON t.id = tm.topic_id
      WHERE tr.topic_id_1 = ? OR tr.topic_id_2 = ?
      ORDER BY tr.co_occurrence_count DESC
      LIMIT ?
    `).bind(topicId, topicId, topicId, limit).all();
    
    return results as TopicWithMetrics[];
  }
}

