-- Oracle (model-generated) answer columns on the answers table.
--
-- The existing `answers` table already stores all answers (human + oracle).
-- These new columns mark answers generated by AI models rather than humans,
-- and carry metadata about the model, cost, and refusal status.
--
-- answer_source: discriminator — 'human' (default for legacy rows) or
--   'oracle_qlaude' / 'oracle_chatqpt' / 'oracle_qemini'
-- oracle_model: the specific model version string from the provider API
--   (e.g. 'claude-opus-4-20250514', 'gpt-4o-2025-05-14')
-- oracle_tokens: total tokens consumed by the model response
-- oracle_cost_qq: $QQ cost as a decimal string (supports fractional $QQ)
-- oracle_refused: 1 if the model refused to answer (safety refusal, etc.)

ALTER TABLE answers ADD COLUMN answer_source TEXT NOT NULL DEFAULT 'human';
ALTER TABLE answers ADD COLUMN oracle_model TEXT;
ALTER TABLE answers ADD COLUMN oracle_tokens INTEGER;
ALTER TABLE answers ADD COLUMN oracle_cost_qq TEXT;
ALTER TABLE answers ADD COLUMN oracle_refused INTEGER NOT NULL DEFAULT 0;

-- Index for efficiently fetching oracle answers per question
CREATE INDEX IF NOT EXISTS idx_answers_oracle_source
  ON answers(q_id, answer_source) WHERE answer_source != 'human';
