/**
 * Auth API Routes
 * 
 * Handles:
 * - POST /api/auth/session - SIWF session creation
 * - POST /api/auth/passkey/register - Register a new passkey user + credential
 * - POST /api/auth/passkey/login - Login with existing passkey
 * - GET /api/auth/passkey/registration/:address - Get registration data for SDK
 * - GET /api/auth/passkey/user - Get current passkey user info (requires auth)
 */

import { AuthService } from '../services/AuthService';
import { requireFlexibleAuth } from '../middleware/auth';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Env = any;

/**
 * Refresh user avatar in KV cache
 * Called at session start to keep avatars fresh without constant API calls
 * Strategy: Refresh avatar when user logs in (every ~7 days), cache for 24 hours between refreshes
 */
async function refreshUserAvatar(env: Env, fid: number): Promise<void> {
  const cacheKey = `user_pfp:${fid}`;

  try {
    // Fetch fresh avatar from Neynar
    const response = await fetch(
      `https://api.neynar.com/v2/farcaster/user/bulk?fids=${fid}`,
      {
        headers: {
          "x-api-key": env.NEYNAR_API_KEY,
          "x-neynar-experimental": "true"
        },
      }
    );

    if (response.ok) {
      const data = await response.json() as { users?: { pfp_url?: string }[] };
      const avatarUrl = data.users?.[0]?.pfp_url;

      if (avatarUrl) {
        // Cache for 24 hours
        await env.KV_USER_PROFILES.put(cacheKey, avatarUrl, {
          expirationTtl: 86400 // 24 hours
        });
        console.log(`[AUTH] ✅ Refreshed avatar for FID ${fid}`);
      }
    } else {
      console.warn(`[AUTH] Neynar API returned ${response.status} for FID ${fid}`);
    }
  } catch (error) {
    console.error(`[AUTH] Error refreshing avatar for FID ${fid}:`, error);
    // Don't throw - avatar refresh is non-critical
  }
}

/**
 * Handle auth-related API routes
 */
export async function handleAuthRoutes(
  request: Request,
  env: Env,
  ctx?: { waitUntil: (p: Promise<any>) => void }
): Promise<Response | null> {
  const url = new URL(request.url);
  const pathname = url.pathname;

  // POST /api/auth/session - Exchange SIWF credentials for a session token
  // Body: { message, signature, nonce }
  // Note: Nonce is generated by SignInButton component, not pre-registered on server
  if (pathname === "/api/auth/session" && request.method === "POST") {
    try {
      const body = await request.json() as {
        message: string;
        signature: string;
        nonce: string;
      };

      console.log(`[AUTH] Session creation request - nonce: ${body.nonce.substring(0, 8)}...`);

      // Verify SIWF credentials
      const authService = AuthService.fromEnv(env, request.url);
      const result = await authService.verifySIWFMessage({
        message: body.message,
        signature: body.signature,
        nonce: body.nonce,
      });

      if (!result.success || !result.fid) {
        console.error(`[AUTH] Session creation failed for nonce ${body.nonce.substring(0, 8)}...: ${result.error}`);
        return Response.json(
          { error: result.error || 'Invalid credentials' },
          { status: 401 }
        );
      }

      // Create a session token (valid for 7 days)
      const sessionToken = crypto.randomUUID();
      const expiresAt = Date.now() + (7 * 24 * 60 * 60 * 1000); // 7 days

      // Store session in KV
      await env.KV_USER_PROFILES.put(
        `session:${sessionToken}`,
        JSON.stringify({ fid: result.fid, expiresAt }),
        { expirationTtl: 7 * 24 * 60 * 60 } // 7 days
      );

      console.log(`[AUTH] ✅ Created session for FID ${result.fid}`);

      // Refresh avatar at session start (background task)
      // This keeps avatars fresh without constant API calls
      if (ctx?.waitUntil) {
        ctx.waitUntil(refreshUserAvatar(env, result.fid));
      } else {
        refreshUserAvatar(env, result.fid).catch(err => {
          console.error(`[AUTH] Avatar refresh failed for FID ${result.fid}:`, err);
        });
      }

      return Response.json({
        sessionToken,
        fid: result.fid,
        expiresAt,
      });
    } catch (e) {
      console.error("[AUTH] Error creating session:", e);
      return Response.json(
        { error: 'Failed to create session' },
        { status: 500 }
      );
    }
  }

  // POST /api/auth/passkey/register - Register a new passkey user + credential
  if (pathname === "/api/auth/passkey/register" && request.method === "POST") {
    try {
      const body = await request.json() as {
        address: string;
        publicKey: string;
        displayName?: string;
        credentialId: string;
        registrationData: unknown;
        deviceName?: string;
        fid?: number;
      };

      if (!body.address || !body.publicKey || !body.credentialId || !body.registrationData) {
        return Response.json(
          { error: 'Missing required fields: address, publicKey, credentialId, registrationData' },
          { status: 400 }
        );
      }

      const { PasskeyAuthService } = await import('../services/PasskeyAuthService');
      const result = await PasskeyAuthService.register(env, {
        address: body.address,
        publicKey: body.publicKey,
        displayName: body.displayName,
        credentialId: body.credentialId,
        registrationData: body.registrationData,
        deviceName: body.deviceName,
        fid: body.fid,
      });

      return Response.json({
        success: true,
        sessionToken: result.sessionToken,
        address: result.address,
        isNewUser: result.isNewUser,
      });
    } catch (e) {
      console.error('[PASSKEY] Registration error:', e);
      return Response.json(
        { error: 'Failed to register passkey' },
        { status: 500 }
      );
    }
  }

      // POST /api/auth/passkey/login - Login with existing passkey
  if (pathname === "/api/auth/passkey/login" && request.method === "POST") {
    try {
      const body = await request.json() as { address?: string; credentialId?: string };

      if (!body.address && !body.credentialId) {
        return Response.json(
          { error: 'Missing required field: address or credentialId' },
          { status: 400 }
        );
      }

      const { PasskeyAuthService } = await import('../services/PasskeyAuthService');

      // If we only have credentialId, resolve to address via registration lookup
      let address = body.address;
      if (body.credentialId && !address) {
        const reg = await env.DB.prepare(
          'SELECT address FROM passkey_registrations WHERE credential_id = ? ORDER BY last_used_at DESC LIMIT 1'
        ).bind(body.credentialId).first() as { address: string } | null;

        if (!reg) {
          return Response.json(
            { error: 'Unknown credential — try creating a passkey first' },
            { status: 404 }
          );
        }
        address = reg.address;
      }

      const result = await PasskeyAuthService.login(env, address!);

      if (!result) {
        return Response.json(
          { error: 'Unknown passkey address' },
          { status: 404 }
        );
      }

      // If FID is linked, fetch real Farcaster profile (fname, pfpUrl)
      let fname = result.fname;
      let pfpUrl: string | null = null;
      if (result.fid && env.NEYNAR_API_KEY) {
        try {
          const neynarRes = await fetch(
            `https://api.neynar.com/v2/farcaster/user/bulk?fids=${result.fid}`,
            { headers: { 'x-api-key': env.NEYNAR_API_KEY, 'x-neynar-experimental': 'true' } }
          );
          if (neynarRes.ok) {
            const neynarData = await neynarRes.json() as { users?: { username?: string; pfp_url?: string; display_name?: string }[] };
            const profile = neynarData.users?.[0];
            if (profile) {
              fname = profile.username || fname;
              pfpUrl = profile.pfp_url || null;
              console.log(`[PASSKEY] \u2705 Resolved FC profile for FID ${result.fid}: ${fname}`);
            }
          }
        } catch (err) {
          console.warn(`[PASSKEY] Neynar lookup failed for FID ${result.fid}:`, err);
          // Non-fatal — continue with DB values
        }
      }

      return Response.json({
        success: true,
        sessionToken: result.sessionToken,
        address: result.address,
        fid: result.fid,
        displayName: result.displayName,
        fname,
        pfpUrl,
      });
    } catch (e) {
      console.error('[PASSKEY] Login error:', e);
      return Response.json(
        { error: 'Failed to login with passkey' },
        { status: 500 }
      );
    }
  }

  // GET /api/auth/passkey/registration/:address - Get registration data for SDK
  if (pathname.startsWith("/api/auth/passkey/registration/") && request.method === "GET") {
    try {
      const address = pathname.split('/').pop();
      if (!address) {
        return Response.json({ error: 'Missing address' }, { status: 400 });
      }

      const { PasskeyAuthService } = await import('../services/PasskeyAuthService');
      const registration = await PasskeyAuthService.getRegistration(env, decodeURIComponent(address));

      if (!registration) {
        return Response.json(
          { error: 'Registration not found' },
          { status: 404 }
        );
      }

      return Response.json(registration);
    } catch (e) {
      console.error('[PASSKEY] Get registration error:', e);
      return Response.json(
        { error: 'Failed to get registration' },
        { status: 500 }
      );
    }
  }

  // GET /api/auth/passkey/user - Get current passkey user info (requires auth)
  if (pathname === "/api/auth/passkey/user" && request.method === "GET") {
    try {
      const auth = await requireFlexibleAuth(request, env);
      if (!auth.authenticated || !auth.passkeyAddress) {
        return Response.json({ error: 'Not authenticated with passkey' }, { status: 401 });
      }

      const { PasskeyAuthService } = await import('../services/PasskeyAuthService');
      const user = await PasskeyAuthService.getUser(env, auth.passkeyAddress);

      if (!user) {
        return Response.json({ error: 'User not found' }, { status: 404 });
      }

      return Response.json(user);
    } catch (e) {
      console.error('[PASSKEY] Get user error:', e);
      return Response.json({ error: 'Failed to get user' }, { status: 500 });
    }
  }

  return null;
}
