// @ts-nocheck
import { VectorService } from './services/VectorService';
import { AIService } from './services/AIService';
import { OGService } from './services/OGService';
import { MetaService } from './services/MetaService';
import { RateLimitService } from './services/RateLimitService';
import { UserSettingsService } from './services/UserSettingsService';
import { NotificationService } from './services/NotificationService';
import { AuthService } from './services/AuthService';
import { createSignerService } from './services/NeynarSignerService';
import { PointsService } from './services/PointsService';
import { UserService } from './services/UserService';
import { SignerService } from './services/SignerService';
import { handleCreateAnswer, handleGetAnswer, handleListAnswers, handleGetUserAnswers, handleUpdateAnswer } from '../src/api/answers';
import { handleAllowlistRoutes } from '../src/api/allowlists';
import { handleCreateQuery, handleGetQuery, handleListQueries } from '../src/api/queries';
import { handleGetNillionConfig, handleGetDelegationToken, handleNotifyPrivateAnswer } from '../src/api/nillion';
import { requireFlexibleAuth } from './middleware/auth';
import { ensureUserExists } from './middleware/userAutoCreate';
import { BetaWhitelistService } from './services/BetaWhitelistService';

interface Env {
  DB: any;
  KV_USER_PROFILES: any;
  KV_USER_POINTS: any;
  QINDEX: any;
  AINDEX: any;
  AI: any;
  ASSETS: any;
  NILLION_ORG_DID: string;
  NILLION_ORG_KEY: string;
  NILLION_NODES: string;
  NILLION_PRIVATE_ANSWER_SCHEMA_ID: string;
  NILLION_ANON_ANSWER_SCHEMA_ID: string;
  NILLION_ALLOWLIST_ANSWER_SCHEMA_ID: string;
  NILLION_ANON_QUERY_ATTRIBUTION_SCHEMA_ID: string;
  NILLION_PROXY_URL: string;
  NILLION_PROXY_SECRET: string;
  HOSTNAME?: string; // For Quick Auth JWT verification
  NEYNAR_API_KEY: string;
  NEYNAR_ANON_BOT_API_KEY: string;
  NEYNAR_ANON_BOT_SIGNER_UUID: string;
  QBASE_SEED_PHRASE: string;
  SPONSOR_SIGNER?: string;
}

// Helper function to check if request is from dev domain
function isDevDomain(request: Request): boolean {
  const hostname = new URL(request.url).hostname;
  return hostname === 'qbase-dev.z00.workers.dev' || hostname === 'localhost';
}

/**
 * Refresh user avatar in KV cache
 * Called at session start to keep avatars fresh without constant API calls
 * Strategy: Refresh avatar when user logs in (every ~7 days), cache for 24 hours between refreshes
 */
async function refreshUserAvatar(env: Env, fid: number): Promise<void> {
  const cacheKey = `user_pfp:${fid}`;

  try {
    // Fetch fresh avatar from Neynar
    const response = await fetch(
      `https://api.neynar.com/v2/farcaster/user/bulk?fids=${fid}`,
      {
        headers: {
          "x-api-key": env.NEYNAR_API_KEY,
          "x-neynar-experimental": "true"
        },
      }
    );

    if (response.ok) {
      const data = await response.json();
      const avatarUrl = data.users?.[0]?.pfp_url;

      if (avatarUrl) {
        // Cache for 24 hours
        await env.KV_USER_PROFILES.put(cacheKey, avatarUrl, {
          expirationTtl: 86400 // 24 hours
        });
        console.log(`[AUTH] ✅ Refreshed avatar for FID ${fid}`);
      }
    } else {
      console.warn(`[AUTH] Neynar API returned ${response.status} for FID ${fid}`);
    }
  } catch (error) {
    console.error(`[AUTH] Error refreshing avatar for FID ${fid}:`, error);
    // Don't throw - avatar refresh is non-critical
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // =========================================================================
    // SECURITY STATUS
    // =========================================================================
    // 1. API Authentication ✓ IMPLEMENTED
    //    - Quick Auth verification is implemented in AuthService
    //    - Frontend uses sdk.quickAuth.getToken() for MiniApp context
    //    - Backend verifies JWT tokens with AuthService.verifyAuthHeader()
    //    - Applied to all protected endpoints:
    //      * /api/check-similarity (POST)
    //      * /api/parse-query (POST)
    //      * /api/answers (POST) with user ID verification
    //      * /api/queries (POST) with coiner ID verification
    //      * /api/farcaster/cast (POST)
    //      * /api/auth/signer (GET, POST)
    //      * /api/auth/signer/register (POST)
    //      * /api/allowlists/* (all methods)
    //
    // 2. Rate Limiting ✓ IMPLEMENTED
    //    - Rate limiting is active on all sensitive endpoints
    //    - Using KV-based rate limiting with IP-based limits
    //    - 60 req/min for reads, 20 req/min for similarity/parse, 10 req/min for writes
    //
    // 3. Cryptographic Signature Verification ✓ IMPLEMENTED
    //    - SIWF signature verification via @farcaster/auth-client
    //    - Nonces generated by SignInButton component (not pre-registered)
    //    - Session tokens for 7-day authentication
    // =========================================================================

    // Meta Tag Injection for Dynamic Routes - MUST BE FIRST, before ASSETS
    // This intercepts the routes before SPA mode in ASSETS handles them
    if (url.pathname.startsWith('/quiz/') || url.pathname.startsWith('/ask/') || url.pathname.startsWith('/question/') || url.pathname === '/questions') {
      try {
        // Manually construct the index.html request
        const indexUrl = new URL('/index.html', url.origin);
        const indexRequest = new Request(indexUrl.toString(), {
          method: 'GET',
          headers: request.headers
        });

        const indexResponse = await env.ASSETS.fetch(indexRequest);

        if (!indexResponse.ok) {
          // If index.html fetch fails, fall back to default handling
          return indexResponse;
        }

        const html = await indexResponse.text();
        let metaTags = '';

        if (url.pathname.startsWith('/quiz/')) {
          const id = url.pathname.split('/')[2];
          if (id) {
            const imageUrl = `${url.origin}/api/og/quiz?id=${id}`;
            const actionUrl = `${url.origin}/quiz/${id}`;
            metaTags = MetaService.generateMiniAppTag(imageUrl, "Take Quiz", actionUrl);
          }
        } else if (url.pathname.startsWith('/ask/')) {
          const username = url.pathname.split('/')[2];
          if (username) {
            const imageUrl = `${url.origin}/api/og/ask?username=${username}`;
            const actionUrl = `${url.origin}/ask/${username}`;
            metaTags = MetaService.generateMiniAppTag(imageUrl, "ask", actionUrl);
          }
        } else if (url.pathname.startsWith('/question/')) {
          const id = url.pathname.split('/')[2];
          if (id) {
            const imageUrl = `${url.origin}/api/og/question?id=${id}`;
            const actionUrl = `${url.origin}/question/${id}`;
            metaTags = MetaService.generateMiniAppTag(imageUrl, "🗣️", actionUrl);
          }
        } else if (url.pathname === '/questions') {
          const imageUrl = `${url.origin}/questions.png`;
          const actionUrl = `${url.origin}/questions`;
          metaTags = MetaService.generateMiniAppTag(imageUrl, "🔍", actionUrl);
        }

        const modifiedHtml = MetaService.injectTags(html, metaTags);

        // Return with proper headers for HTML
        return new Response(modifiedHtml, {
          headers: {
            'Content-Type': 'text/html;charset=UTF-8',
            'Cache-Control': 'public, max-age=0, must-revalidate'
          },
          status: indexResponse.status
        });
      } catch (e) {
        console.error('Meta Tag Injection Error:', e);
        // Fall back to ASSETS on error
        return env.ASSETS.fetch(request);
      }
    }

    // OG Image Generation Routes
    if (url.pathname.startsWith('/api/og/')) {
      const type = url.pathname.split('/')[3];
      const searchParams = url.searchParams;

      try {
        let imageBuffer: Uint8Array;

        if (type === 'quiz') {
          const id = searchParams.get('id');
          if (!id) return new Response('Missing id', { status: 400 });

          const quiz = await env.DB.prepare('SELECT * FROM quizzes WHERE id = ?').bind(id).first();
          if (!quiz) return new Response('Quiz not found', { status: 404 });

          const creator = await env.DB.prepare('SELECT * FROM users WHERE id = ?').bind((quiz as { creator_id: number }).creator_id).first() as { fname?: string } | null;
          const creatorName = creator ? (creator.fname || 'Unknown') : 'Unknown';

          const qCount = 5; // Placeholder

          imageBuffer = OGService.generateQuizImage((quiz as { title: string }).title, creatorName, qCount);
        } else if (type === 'ask') {
          const username = searchParams.get('username');
          if (!username) return new Response('Missing username', { status: 400 });

          // Look up user by username to get FID
          const user = await env.DB.prepare(
            'SELECT fid FROM Users WHERE fname = ?'
          ).bind(username).first() as { fid: number } | null;

          if (!user) return new Response('User not found', { status: 404 });

          // Try to get profile from KV first
          let profileStr = await env.KV_USER_PROFILES.get(user.fid.toString());
          let profile: { username: string; displayName: string; pfp_url?: string };

          if (profileStr) {
            profile = JSON.parse(profileStr) as { username: string; displayName: string; pfp_url?: string };
          } else {
            // If not in KV, fetch from Neynar
            try {
              const { NeynarService } = await import('../src/services/NeynarService');
              const neynarUsers = await NeynarService.fetchBulkUsers([user.fid.toString()], env.NEYNAR_API_KEY);
              const neynarUser = neynarUsers[0];

              if (neynarUser) {
                profile = {
                  username: neynarUser.username,
                  displayName: neynarUser.display_name,
                  pfp_url: neynarUser.pfp_url
                };

                // Cache it for next time
                await env.KV_USER_PROFILES.put(
                  user.fid.toString(),
                  JSON.stringify(profile),
                  { expirationTtl: 86400 } // 24 hours
                );
              } else {
                profile = { username, displayName: username };
              }
            } catch (error) {
              console.error('Error fetching profile from Neynar:', error);
              profile = { username, displayName: username };
            }
          }

          // Get answer count for this user
          const answerCountResult = await env.DB.prepare(
            'SELECT COUNT(*) as count FROM answers WHERE user_id = (SELECT id FROM Users WHERE fname = ?)'
          ).bind(username).first() as { count: number } | null;
          const answerCount = answerCountResult?.count || 0;

          const pointsService = PointsService.fromEnv(env);
          const points = await pointsService.getPoints(user.fid);
          const totalXp = pointsService.getTotalSpendable(points);

          imageBuffer = await OGService.generateProfileImage(profile.username, profile.pfp_url);
        } else if (type === 'question') {
          const id = searchParams.get('id');
          if (!id) return new Response('Missing id', { status: 400 });

          const question = await env.DB.prepare('SELECT * FROM queries WHERE id = ?').bind(id).first();
          if (!question) return new Response('Question not found', { status: 404 });

          imageBuffer = OGService.generateQuestionImage((question as { stem: string; coiner_fname?: string }).stem, (question as { coiner_fname?: string }).coiner_fname || 'Unknown');
        } else if (type === 'questions') {
          // Serve static image for /questions page
          const imageUrl = new URL('/questions.png', url.origin);
          const imageRequest = new Request(imageUrl.toString());
          const imageResponse = await env.ASSETS.fetch(imageRequest);
          
          if (!imageResponse.ok) {
            return new Response('Questions image not found', { status: 404 });
          }
          
          // Return the static image directly
          return new Response(imageResponse.body, {
            headers: {
              'Content-Type': 'image/png',
              'Cache-Control': 'public, max-age=31536000, immutable'
            }
          });
        } else {
          return new Response('Invalid OG type', { status: 400 });
        }

        return new Response(imageBuffer, {
          headers: {
            'Content-Type': 'image/png',
            'Cache-Control': 'public, max-age=3600'
          }
        });

      } catch (e) {
        console.error('OG Generation Error:', e);
        return new Response('Error generating image', { status: 500 });
      }
    }

    // =========================================================================
    // NEYNAR SIGNER AUTHENTICATION ENDPOINTS
    // =========================================================================

    // POST /api/auth/session - Exchange SIWF credentials for a session token
    // Body: { message, signature, nonce }
    // Note: Nonce is generated by SignInButton component, not pre-registered on server
    if (url.pathname === "/api/auth/session" && request.method === "POST") {
      try {
        const body = await request.json() as {
          message: string;
          signature: string;
          nonce: string;
        };

        console.log(`[AUTH] Session creation request - nonce: ${body.nonce.substring(0, 8)}...`);

        // Verify SIWF credentials
        const authService = AuthService.fromEnv(env, request.url);
        const result = await authService.verifySIWFMessage({
          message: body.message,
          signature: body.signature,
          nonce: body.nonce,
        });

        if (!result.success || !result.fid) {
          console.error(`[AUTH] Session creation failed for nonce ${body.nonce.substring(0, 8)}...: ${result.error}`);
          return Response.json(
            { error: result.error || 'Invalid credentials' },
            { status: 401 }
          );
        }

        // Create a session token (valid for 7 days)
        const sessionToken = crypto.randomUUID();
        const expiresAt = Date.now() + (7 * 24 * 60 * 60 * 1000); // 7 days

        // Store session in KV
        await env.KV_USER_PROFILES.put(
          `session:${sessionToken}`,
          JSON.stringify({ fid: result.fid, expiresAt }),
          { expirationTtl: 7 * 24 * 60 * 60 } // 7 days
        );

        console.log(`[AUTH] ✅ Created session for FID ${result.fid}`);

        // Refresh avatar at session start (background task)
        // This keeps avatars fresh without constant API calls
        refreshUserAvatar(env, result.fid).catch(err => {
          console.error(`[AUTH] Avatar refresh failed for FID ${result.fid}:`, err);
          // Don't block session creation if avatar refresh fails
        });

        return Response.json({
          sessionToken,
          fid: result.fid,
          expiresAt,
        });
      } catch (e) {
        console.error("[AUTH] Error creating session:", e);
        return Response.json(
          { error: 'Failed to create session' },
          { status: 500 }
        );
      }
    }

    // GET /api/auth/signers - Fetch user's existing signers by FID
    // Query params: fid (Farcaster ID)
    // Note: For web users authenticated via SIWF, the FID comes from the verified auth-kit flow
    // For miniapp users, this is protected by Quick Auth middleware
    if (url.pathname === "/api/auth/signers" && request.method === "GET") {
      try {
        const fidParam = url.searchParams.get('fid');

        if (!fidParam) {
          return Response.json(
            { error: 'FID is required' },
            { status: 400 }
          );
        }

        const fid = parseInt(fidParam, 10);
        if (isNaN(fid)) {
          return Response.json(
            { error: 'Invalid FID' },
            { status: 400 }
          );
        }

        // Get signers from database
        const signers = await SignerService.getSignersByFid(env, fid);

        return Response.json({
          signers: signers || [],
          fid,
        });
      } catch (e) {
        console.error("Error fetching signers:", e);
        return Response.json(
          { error: 'Failed to fetch signers' },
          { status: 500 }
        );
      }
    }

    // POST /api/auth/signer - Create a new signer (requires auth)
    if (url.pathname === "/api/auth/signer" && request.method === "POST") {
      try {
        // Verify authentication
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated) {
          return new Response(auth.error || "Unauthorized", { status: 401 });
        }

        if (!env.NEYNAR_API_KEY) {
          console.error('[Signer] NEYNAR_API_KEY not configured');
          return Response.json(
            { error: 'Server configuration error: NEYNAR_API_KEY missing' },
            { status: 500 }
          );
        }

        // Revoke any existing pending signers before creating new one
        // This prevents accumulation of abandoned pending signers from failed attempts
        await env.DB.prepare(`
          UPDATE user_signers
          SET status = 'revoked', updated_at = CURRENT_TIMESTAMP
          WHERE fid = ? AND status = 'pending_approval'
        `).bind(auth.fid!).run();

        const signerService = createSignerService(env.NEYNAR_API_KEY);
        const signer = await signerService.createSigner();

        // Save new signer to database
        await SignerService.saveSigner(
          env,
          auth.fid!,
          signer.signer_uuid,
          signer.public_key,
          'pending_approval'
        );

        return Response.json(signer);
      } catch (e) {
        console.error("[Signer] Error creating signer:", e);
        return Response.json(
          { error: 'Failed to create signer', details: e instanceof Error ? e.message : String(e) },
          { status: 500 }
        );
      }
    }

    // GET /api/auth/signer - Poll signer status by UUID (requires auth)
    // Query params: signerUuid
    if (url.pathname === "/api/auth/signer" && request.method === "GET") {
      try {
        // Verify authentication
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated) {
          return new Response(auth.error || "Unauthorized", { status: 401 });
        }

        const signerUuid = url.searchParams.get('signerUuid');

        if (!signerUuid) {
          return Response.json(
            { error: 'signerUuid is required' },
            { status: 400 }
          );
        }

        const signerService = createSignerService(env.NEYNAR_API_KEY);
        const signer = await signerService.lookupSigner(signerUuid);

        // Update status in database
        await SignerService.updateSignerStatus(env, signerUuid, signer.status);

        return Response.json(signer);
      } catch (e) {
        console.error("Error looking up signer:", e);
        return Response.json(
          { error: 'Failed to lookup signer' },
          { status: 500 }
        );
      }
    }

    // POST /api/auth/signer/register - Register signed key with Farcaster (requires auth)
    // Body: { signerUuid, publicKey }
    if (url.pathname === "/api/auth/signer/register" && request.method === "POST") {
      try {
        // Verify authentication
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated) {
          return new Response(auth.error || "Unauthorized", { status: 401 });
        }

        const body = await request.json() as { signerUuid: string; publicKey: string };
        const { signerUuid, publicKey } = body;

        if (!signerUuid || !publicKey) {
          return Response.json(
            { error: 'signerUuid and publicKey are required' },
            { status: 400 }
          );
        }

        if (!env.QBASE_SEED_PHRASE) {
          console.error('[Signer] QBASE_SEED_PHRASE not configured');
          return Response.json(
            { error: 'Server configuration error: QBASE_SEED_PHRASE missing' },
            { status: 500 }
          );
        }

        const signerService = createSignerService(env.NEYNAR_API_KEY);
        const sponsorSigner = env.SPONSOR_SIGNER === 'true';

        const result = await signerService.registerSignedKey(
          signerUuid,
          publicKey,
          env.QBASE_SEED_PHRASE,
          sponsorSigner
        );

        return Response.json(result);
      } catch (e) {
        console.error("[Signer] Error registering signed key:", e);
        return Response.json(
          { error: 'Failed to register signed key', details: e instanceof Error ? e.message : String(e) },
          { status: 500 }
        );
      }
    }

    // GET /api/beta/check - Check if user is whitelisted for beta access
    // Returns whitelist status for the authenticated user
    if (url.pathname === "/api/beta/check" && request.method === "GET") {
      try {
        // Verify authentication (flexible: JWT or SIWF)
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated || !auth.fid) {
          return Response.json(
            { whitelisted: false, error: 'Not authenticated' },
            { status: 401 }
          );
        }

        const whitelisted = await BetaWhitelistService.isWhitelisted(env, auth.fid);
        const isAdmin = BetaWhitelistService.isAdmin(auth.fid);

        return Response.json({
          whitelisted,
          isAdmin,
          fid: auth.fid,
        });
      } catch (e) {
        console.error("[Beta] Error checking whitelist:", e);
        return Response.json(
          { error: 'Failed to check whitelist status' },
          { status: 500 }
        );
      }
    }

    // Beta Whitelist Admin endpoints
    if (url.pathname.startsWith("/api/admin/beta-whitelist")) {
      // All admin endpoints require authentication
      const auth = await requireFlexibleAuth(request, env);
      if (!auth.authenticated || !auth.fid) {
        return new Response("Unauthorized", { status: 401 });
      }

      // Only admins can access these endpoints
      if (!BetaWhitelistService.isAdmin(auth.fid)) {
        return new Response("Forbidden: Admin access required", { status: 403 });
      }

      // GET /api/admin/beta-whitelist - List all whitelisted users
      if (url.pathname === "/api/admin/beta-whitelist" && request.method === "GET") {
        try {
          const limit = parseInt(url.searchParams.get('limit') || '100', 10);
          const offset = parseInt(url.searchParams.get('offset') || '0', 10);
          
          const result = await BetaWhitelistService.listWhitelist(env, limit, offset);
          return Response.json(result);
        } catch (e) {
          console.error("[Beta Admin] Error listing whitelist:", e);
          return Response.json({ error: 'Failed to list whitelist' }, { status: 500 });
        }
      }

      // POST /api/admin/beta-whitelist - Add user(s) to whitelist
      // Body: { fid?: number, fids?: string (comma-separated), fname?: string, notes?: string }
      // Automatically fetches username from Neynar if not provided
      if (url.pathname === "/api/admin/beta-whitelist" && request.method === "POST") {
        try {
          const body = await request.json() as {
            fid?: number;
            fids?: string; // Comma-separated list for bulk add
            fname?: string;
            notes?: string;
          };

          // Helper to fetch username from Neynar
          const fetchUsername = async (fid: number): Promise<string | undefined> => {
            try {
              const response = await fetch(
                `https://api.neynar.com/v2/farcaster/user/bulk?fids=${fid}`,
                {
                  headers: {
                    "x-api-key": env.NEYNAR_API_KEY,
                    "x-neynar-experimental": "true"
                  },
                }
              );
              if (response.ok) {
                const data = await response.json() as { users?: { username?: string }[] };
                return data.users?.[0]?.username;
              }
            } catch (e) {
              console.error(`[Beta Admin] Failed to fetch username for FID ${fid}:`, e);
            }
            return undefined;
          };

          // Bulk add if fids provided
          if (body.fids) {
            const result = await BetaWhitelistService.addBulkToWhitelist(
              env,
              body.fids,
              auth.fid,
              fetchUsername
            );
            return Response.json({
              success: true,
              added: result.added,
              failed: result.failed,
              message: `Added ${result.added.length} FIDs to whitelist`
            });
          }

          // Single add if fid provided
          if (body.fid) {
            // Fetch username from Neynar if not provided
            let fname = body.fname;
            if (!fname) {
              fname = await fetchUsername(body.fid);
            }
            
            const entry = await BetaWhitelistService.addToWhitelist(
              env,
              body.fid,
              auth.fid,
              fname,
              body.notes
            );
            return Response.json({
              success: true,
              entry,
            });
          }

          return Response.json(
            { error: 'Either fid or fids is required' },
            { status: 400 }
          );
        } catch (e) {
          console.error("[Beta Admin] Error adding to whitelist:", e);
          return Response.json({ error: 'Failed to add to whitelist' }, { status: 500 });
        }
      }

      // DELETE /api/admin/beta-whitelist/:fid - Remove user from whitelist
      const deleteMatch = url.pathname.match(/^\/api\/admin\/beta-whitelist\/(\d+)$/);
      if (deleteMatch && request.method === "DELETE") {
        try {
          const fid = parseInt(deleteMatch[1], 10);
          const deleted = await BetaWhitelistService.removeFromWhitelist(env, fid);
          
          return Response.json({
            success: deleted,
            fid,
            message: deleted ? 'Removed from whitelist' : 'User was not in whitelist'
          });
        } catch (e) {
          console.error("[Beta Admin] Error removing from whitelist:", e);
          return Response.json({ error: 'Failed to remove from whitelist' }, { status: 500 });
        }
      }

      return new Response("Not Found", { status: 404 });
    }

    // POST /api/users - Create or update user record (requires auth)
    // Body: { fid, fname, displayName?, pfpUrl?, primaryAddress? }
    // This endpoint is called after successful authentication to ensure user exists in DB
    // Supports both JWT (MiniApp) and SIWF (Web) authentication
    if (url.pathname === "/api/users" && request.method === "POST") {
      try {
        // Verify authentication (flexible: JWT or SIWF)
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated) {
          return new Response(auth.error || "Unauthorized", { status: 401 });
        }

        const body = await request.json() as {
          fid: number;
          fname: string;
          displayName?: string;
          pfpUrl?: string;
          primaryAddress?: string;
        };

        // Verify the authenticated user is creating/updating their own record
        if (body.fid !== auth.fid) {
          return Response.json(
            { error: 'Cannot create/update user record for different FID' },
            { status: 403 }
          );
        }

        // Check if user already exists in DB
        const existingUser = await UserService.getByFid(env, body.fid);
        
        // If user doesn't exist, check whitelist before creating
        if (!existingUser) {
          const isWhitelisted = await BetaWhitelistService.isWhitelisted(env, body.fid);
          if (!isWhitelisted) {
            return Response.json(
              { 
                error: 'Beta access required',
                code: 'BETA_ACCESS_REQUIRED',
                message: 'qbase is currently in beta. You need to be on the whitelist to create an account.'
              },
              { status: 403 }
            );
          }
        }

        // Upsert user
        const user = await UserService.upsert(env, {
          fid: body.fid,
          fname: body.fname,
          displayName: body.displayName,
          pfpUrl: body.pfpUrl,
          primaryAddress: body.primaryAddress,
        });

        return Response.json({
          success: true,
          user: {
            id: user.id,
            fid: user.fid,
            fname: user.fname,
            created_at: user.created_at,
          }
        });
      } catch (e) {
        console.error("Error creating/updating user:", e);
        return Response.json(
          { error: 'Failed to create/update user' },
          { status: 500 }
        );
      }
    }

    // POST /api/farcaster/cast - Publish a cast using an approved signer
    // Body: { signerUuid?, useAnonBot?, text, embeds?, parent?, parentAuthorFid?, entityType?, entityId? }
    // Supports both user casts (requires auth + signerUuid) and anon bot casts (useAnonBot: true)
    if (url.pathname === "/api/farcaster/cast" && request.method === "POST") {
      try {
        const body = await request.json() as {
          signerUuid?: string;        // User's signer (for regular casts)
          useAnonBot?: boolean;       // Flag to use anon bot
          text: string;
          embeds?: { url: string }[];
          parent?: string;            // Parent cast hash (for replies)
          parentAuthorFid?: number;   // Parent cast author FID (for replies)
          entityType?: 'query' | 'answer';  // Optional: type of entity being casted
          entityId?: string;          // Optional: ID of entity being casted
        };
        const { signerUuid, useAnonBot, text, embeds, parent, parentAuthorFid, entityType, entityId } = body;

        if (!text) {
          return Response.json(
            { error: 'text is required' },
            { status: 400 }
          );
        }

        let effectiveSignerUuid: string;
        let apiKey: string;

        if (useAnonBot) {
          // Use anon bot signer and separate API key (no auth required)
          if (!env.NEYNAR_ANON_BOT_SIGNER_UUID) {
            return Response.json(
              { error: 'Anon bot signer not configured' },
              { status: 500 }
            );
          }
          if (!env.NEYNAR_ANON_BOT_API_KEY) {
            return Response.json(
              { error: 'Anon bot API key not configured' },
              { status: 500 }
            );
          }
          effectiveSignerUuid = env.NEYNAR_ANON_BOT_SIGNER_UUID;
          apiKey = env.NEYNAR_ANON_BOT_API_KEY;
          console.log('Posting cast from anon bot (@4n0n)');
        } else {
          // Regular user cast - requires authentication
          const auth = await requireFlexibleAuth(request, env);
          if (!auth.authenticated) {
            return new Response(auth.error || "Unauthorized", { status: 401 });
          }

          if (!signerUuid) {
            return Response.json(
              { error: 'signerUuid required for user casts' },
              { status: 400 }
            );
          }

          effectiveSignerUuid = signerUuid;
          apiKey = env.NEYNAR_API_KEY;
        }

        const signerService = createSignerService(apiKey);
        const result = await signerService.publishCast(effectiveSignerUuid, text, embeds, parent, parentAuthorFid);

        // Store cast hash in database if entity info provided
        if (entityType && entityId && result.cast?.hash) {
          try {
            const { FarcasterDBService } = await import('./services/FarcasterDBService');
            const { anon_fid } = await import('../src/lib/consts');

            // Determine caster FID and username
            let casterFid: number;
            let casterUsername: string;

            if (useAnonBot) {
              casterFid = anon_fid;
              casterUsername = '4n0n';
            } else {
              // Get user info from auth
              const auth = await requireFlexibleAuth(request, env);
              casterFid = auth.user?.fid || 0;
              casterUsername = auth.user?.username || 'user';
            }

            await FarcasterDBService.upsertCast(env.DB, {
              entity_type: entityType,
              entity_id: entityId,
              cast_hash: result.cast.hash,
              cast_url: `https://farcaster.xyz/${casterUsername}/${result.cast.hash}`,
              caster_fid: casterFid,
            });

            console.log(`Stored cast hash for ${entityType} ${entityId} in database`);
          } catch (dbError) {
            // Don't fail the cast if DB storage fails
            console.error('Failed to store cast hash in database:', dbError);
          }
        }

        return Response.json(result);
      } catch (e) {
        console.error("Error publishing cast:", e);
        return Response.json(
          { error: 'Failed to publish cast' },
          { status: 500 }
        );
      }
    }

    // POST /api/farcaster/like - Like or unlike a cast (requires auth + signer)
    if (url.pathname === "/api/farcaster/like" && request.method === "POST") {
      try {
        // Verify authentication
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated) {
          return new Response(auth.error || "Unauthorized", { status: 401 });
        }

        const body = await request.json() as {
          signerUuid: string;
          castHash: string;
          action: 'like' | 'unlike';
        };
        const { signerUuid, castHash, action } = body;

        if (!signerUuid || !castHash || !action) {
          return Response.json(
            { error: 'signerUuid, castHash, and action are required' },
            { status: 400 }
          );
        }

        const signerService = createSignerService(env.NEYNAR_API_KEY);

        if (action === 'like') {
          const result = await signerService.likeCast(signerUuid, castHash);

          // Store reaction in database
          const { FarcasterDBService } = await import('./services/FarcasterDBService');
          await FarcasterDBService.upsertReaction(env.DB, {
            cast_hash: castHash,
            reactor_fid: auth.fid || result.reaction.reactor_fid,
            reaction_type: 'like',
            source: 'qbase',
          });

          return Response.json(result);
        } else {
          const result = await signerService.unlikeCast(signerUuid, castHash);

          // Remove reaction from database
          const { FarcasterDBService } = await import('./services/FarcasterDBService');
          await FarcasterDBService.deleteReaction(env.DB, castHash, auth.fid || 0, 'like');

          return Response.json(result);
        }
      } catch (e) {
        console.error("Error handling like action:", e);
        return Response.json(
          { error: 'Failed to process like action' },
          { status: 500 }
        );
      }
    }

    // POST /api/farcaster/recast - Recast or unrecast a cast (requires auth + signer)
    if (url.pathname === "/api/farcaster/recast" && request.method === "POST") {
      try {
        // Verify authentication
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated) {
          return new Response(auth.error || "Unauthorized", { status: 401 });
        }

        const body = await request.json() as {
          signerUuid: string;
          castHash: string;
          action: 'recast' | 'unrecast';
        };
        const { signerUuid, castHash, action } = body;

        if (!signerUuid || !castHash || !action) {
          return Response.json(
            { error: 'signerUuid, castHash, and action are required' },
            { status: 400 }
          );
        }

        const signerService = createSignerService(env.NEYNAR_API_KEY);

        if (action === 'recast') {
          const result = await signerService.recast(signerUuid, castHash);

          // Store reaction in database
          const { FarcasterDBService } = await import('./services/FarcasterDBService');
          await FarcasterDBService.upsertReaction(env.DB, {
            cast_hash: castHash,
            reactor_fid: auth.fid || result.reaction.reactor_fid,
            reaction_type: 'recast',
            source: 'qbase',
          });

          return Response.json(result);
        } else {
          const result = await signerService.unrecast(signerUuid, castHash);

          // Remove reaction from database
          const { FarcasterDBService } = await import('./services/FarcasterDBService');
          await FarcasterDBService.deleteReaction(env.DB, castHash, auth.fid || 0, 'recast');

          return Response.json(result);
        }
      } catch (e) {
        console.error("Error handling recast action:", e);
        return Response.json(
          { error: 'Failed to process recast action' },
          { status: 500 }
        );
      }
    }

    // GET /api/user/:fid/avatar - Get user avatar from KV cache
    if (url.pathname.match(/^\/api\/user\/\d+\/avatar$/) && request.method === "GET") {
      const fid = parseInt(url.pathname.split('/')[3], 10);

      if (isNaN(fid)) {
        return Response.json({ error: 'Invalid FID' }, { status: 400 });
      }

      try {
        const cacheKey = `user_pfp:${fid}`;
        let avatarUrl = await env.KV_USER_PROFILES.get(cacheKey);

        // If not in cache, fetch from Neynar and cache it
        if (!avatarUrl) {
          const neynarResponse = await fetch(
            `https://api.neynar.com/v2/farcaster/user/bulk?fids=${fid}`,
            {
              headers: {
                "x-api-key": env.NEYNAR_API_KEY,
                "x-neynar-experimental": "true"
              },
            }
          );

          if (neynarResponse.ok) {
            const data = await neynarResponse.json();
            avatarUrl = data.users?.[0]?.pfp_url || null;

            // Cache for 24 hours
            if (avatarUrl) {
              await env.KV_USER_PROFILES.put(cacheKey, avatarUrl, {
                expirationTtl: 86400
              });
            }
          }
        }

        return Response.json({ avatarUrl });
      } catch (error) {
        console.error(`Error fetching avatar for FID ${fid}:`, error);
        return Response.json({ avatarUrl: null }, { status: 200 }); // Return null on error, don't fail
      }
    }

    // GET /api/farcaster/conversation/:castHash - Fetch cast conversation/replies
    const conversationMatch = url.pathname.match(/^\/api\/farcaster\/conversation\/([a-zA-Z0-9]+)$/);
    if (conversationMatch && request.method === "GET") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      try {
        const castHash = conversationMatch[1];
        const viewerFid = url.searchParams.get('viewer_fid');
        const limit = parseInt(url.searchParams.get('limit') || '25');
        
        const signerService = createSignerService(env.NEYNAR_API_KEY);
        const conversation = await signerService.getCastConversation(
          castHash,
          viewerFid ? parseInt(viewerFid) : undefined,
          1, // reply depth
          Math.min(limit, 50) // cap at 50
        );

        // If conversation is null, the cast was deleted on Farcaster
        if (conversation === null) {
          // Clear the cast_hash from the queries table
          try {
            await env.DB.prepare(
              "UPDATE Queries SET cast_hash = NULL WHERE cast_hash = ?"
            ).bind(castHash).run();
            console.log(`[Farcaster] Cleared deleted cast_hash ${castHash} from queries table`);
          } catch (dbError) {
            console.error('Error clearing deleted cast_hash from DB:', dbError);
          }

          // Return empty conversation structure
          return Response.json({
            cast: null,
            replies: [],
            deleted: true,
          });
        }

        return Response.json(conversation);
      } catch (error) {
        console.error("Error fetching cast conversation:", error);
        return Response.json(
          { error: 'Failed to fetch conversation' },
          { status: 500 }
        );
      }
    }

    // POST /api/farcaster/sync-stats - Update cached Farcaster engagement stats for a cast
    // Body: { castHash, likes_count, recasts_count, replies_count, pub_answers? }
    if (url.pathname === "/api/farcaster/sync-stats" && request.method === "POST") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 30, 60); // 30 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      try {
        const body = await request.json() as {
          castHash: string;
          likes_count: number;
          recasts_count: number;
          replies_count: number;
          pub_answers?: number;
        };
        const { castHash, likes_count, recasts_count, replies_count, pub_answers } = body;

        if (!castHash) {
          return Response.json(
            { error: 'castHash is required' },
            { status: 400 }
          );
        }

        // Validate counts are non-negative numbers
        if (typeof likes_count !== 'number' || typeof recasts_count !== 'number' || typeof replies_count !== 'number') {
          return Response.json(
            { error: 'likes_count, recasts_count, and replies_count must be numbers' },
            { status: 400 }
          );
        }

        const { FarcasterDBService } = await import('./services/FarcasterDBService');
        const updated = await FarcasterDBService.updateCachedStats(env.DB, castHash, {
          likes_count: Math.max(0, likes_count),
          recasts_count: Math.max(0, recasts_count),
          replies_count: Math.max(0, replies_count),
        });

        // Also update pub_answers on the queries table if provided
        let pubAnswersUpdated = false;
        if (typeof pub_answers === 'number' && pub_answers >= 0) {
          // Look up the query ID from the cast hash
          const cast = await FarcasterDBService.getCastByHash(env.DB, castHash);
          if (cast && cast.entity_type === 'query') {
            await env.DB.prepare(
              'UPDATE queries SET pub_answers = ? WHERE id = ?'
            ).bind(Math.max(0, pub_answers), cast.entity_id).run();
            pubAnswersUpdated = true;
            console.log(`[Farcaster Stats] Updated pub_answers to ${pub_answers} for query ${cast.entity_id}`);
          }
        }

        if (!updated) {
          // Cast not found in our database, that's OK - just log it
          console.log(`[Farcaster Stats] No cast found for hash ${castHash}, skipping stats update`);
        }

        return Response.json({
          success: true,
          updated,
          pubAnswersUpdated,
          castHash,
          stats: { likes_count, recasts_count, replies_count, pub_answers }
        });
      } catch (error) {
        console.error("Error updating Farcaster stats:", error);
        return Response.json(
          { error: 'Failed to update Farcaster stats' },
          { status: 500 }
        );
      }
    }

    // POST /api/farcaster/follow - Follow or unfollow a user (requires auth + signer)
    if (url.pathname === "/api/farcaster/follow" && request.method === "POST") {
      try {
        // Verify authentication
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated) {
          return new Response(auth.error || "Unauthorized", { status: 401 });
        }

        const body = await request.json() as {
          signerUuid: string;
          targetFid: number;
          action: 'follow' | 'unfollow';
        };
        const { signerUuid, targetFid, action } = body;

        if (!signerUuid || !targetFid || !action) {
          return Response.json(
            { error: 'signerUuid, targetFid, and action are required' },
            { status: 400 }
          );
        }

        if (typeof targetFid !== 'number' || targetFid <= 0) {
          return Response.json(
            { error: 'targetFid must be a positive number' },
            { status: 400 }
          );
        }

        const signerService = createSignerService(env.NEYNAR_API_KEY);

        if (action === 'follow') {
          const result = await signerService.followUser(signerUuid, targetFid);
          return Response.json(result);
        } else {
          const result = await signerService.unfollowUser(signerUuid, targetFid);
          return Response.json(result);
        }
      } catch (e) {
        console.error("Error handling follow action:", e);
        return Response.json(
          { error: 'Failed to process follow action' },
          { status: 500 }
        );
      }
    }

    // POST /api/check-similarity - Check if query text is similar to existing queries (requires auth)
    if (url.pathname === "/api/check-similarity" && request.method === "POST") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 20, 60); // 20 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      // Verify authentication
      const auth = await requireFlexibleAuth(request, env);
      if (!auth.authenticated) {
        return new Response(auth.error || "Unauthorized", { status: 401 });
      }

      try {
        const { text } = await request.json() as { text: string };

        if (!text) {
          return new Response("Missing text", { status: 400 });
        }

        const vectorService = VectorService.fromEnv(env);
        const result = await vectorService.checkSimilarity(text);

        return Response.json(result);
      } catch (error) {
        console.error("Error checking similarity:", error);
        return new Response("Internal Server Error", { status: 500 });
      }

    }

    // POST /api/parse-query - Parse query text using AI (requires auth)
    if (url.pathname === "/api/parse-query" && request.method === "POST") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 20, 60); // 20 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      // Verify authentication
      const auth = await requireFlexibleAuth(request, env);
      if (!auth.authenticated) {
        return new Response(auth.error || "Unauthorized", { status: 401 });
      }

      try {
        const { text } = await request.json() as { text: string };

        if (!text) {
          return new Response("Missing text", { status: 400 });
        }

        const aiService = AIService.fromEnv(env);
        const result = await aiService.parseQuery(text);

        return Response.json(result);
      } catch (error) {
        console.error("Error parsing query:", error);
        return new Response("Internal Server Error", { status: 500 });
      }
    }

    // =========================================================================
    // NILLION E2E ENCRYPTION ENDPOINTS
    // =========================================================================

    // GET /api/nillion/config - Get Nillion config for client-side E2E operations
    if (url.pathname === "/api/nillion/config" && request.method === "GET") {
      return handleGetNillionConfig(request, env);
    }

    // POST /api/nillion/delegation-token - Get delegation token for E2E encrypted answers
    if (url.pathname === "/api/nillion/delegation-token" && request.method === "POST") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 10, 60); // 10 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }
      return handleGetDelegationToken(request, env);
    }

    // POST /api/answers/notify-private - Notify server of E2E encrypted answer (bookkeeping only)
    if (url.pathname === "/api/answers/notify-private" && request.method === "POST") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 30, 60); // 30 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }
      return handleNotifyPrivateAnswer(request, env);
    }

    // =========================================================================
    // ANSWER ENDPOINTS
    // =========================================================================

    // POST /api/answers - Submit an answer (requires auth)
    if (url.pathname === "/api/answers" && request.method === "POST") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 30, 60); // 30 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      // Verify authentication
      const auth = await requireFlexibleAuth(request, env);
      if (!auth.authenticated) {
        return new Response(auth.error || "Unauthorized", { status: 401 });
      }

      // Inject user_id from authenticated user (similar to query creation)
      try {
        const body = await request.json() as Omit<{ user_id: number }, 'user_id'>;

        // Ensure user exists in DB (auto-create if needed)
        const userRow = await ensureUserExists(env, auth.fid);

        if (!userRow) {
          return new Response('Failed to create/retrieve user', { status: 500 });
        }

        // Inject authenticated user's internal ID into the request body
        // This prevents client manipulation of user identity
        const verifiedBody = {
          ...body,
          user_id: userRow.id, // Internal DB ID from authenticated user
        };

        // Re-create the request with the verified body for the handler
        const verifiedRequest = new Request(request.url, {
          method: request.method,
          headers: request.headers,
          body: JSON.stringify(verifiedBody)
        });

        return handleCreateAnswer(verifiedRequest, env);
      } catch (e) {
        console.error('Error validating answer request:', e);
        return new Response('Invalid request', { status: 400 });
      }
    }

    // Allowlist CRUD endpoints (authenticated)
    if (url.pathname.startsWith("/api/allowlists")) {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 20, 60); // 20 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      return handleAllowlistRoutes(request, env);
    }

    // Miniapp Status endpoints (authenticated)
    if (url.pathname === "/api/miniapp/status") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      // Verify authentication
      const auth = await requireFlexibleAuth(request, env);
      if (!auth.authenticated) {
        return new Response(auth.error || "Unauthorized", { status: 401 });
      }

      // GET /api/miniapp/status - Check if user has added miniapp
      if (request.method === "GET") {
        try {
          const key = `miniapp_added:${auth.fid}`;
          const value = await env.KV_USER_PROFILES.get(key);
          const miniAppAdded = value === 'true';

          return Response.json({ miniAppAdded });
        } catch (error) {
          console.error("Error checking miniapp status:", error);
          return new Response("Internal Server Error", { status: 500 });
        }
      }

      // POST /api/miniapp/status - Update miniapp add/remove status
      if (request.method === "POST") {
        try {
          const body = await request.json();
          const { added } = body as { added: boolean };

          const key = `miniapp_added:${auth.fid}`;
          await env.KV_USER_PROFILES.put(key, added ? 'true' : 'false');

          console.log(`Marked miniapp as ${added ? 'added' : 'removed'} for FID ${auth.fid}`);

          return Response.json({ success: true, miniAppAdded: added });
        } catch (error) {
          console.error("Error updating miniapp status:", error);
          return new Response("Internal Server Error", { status: 500 });
        }
      }

      return new Response("Method Not Allowed", { status: 405 });
    }

    // Miniapp Notification Status endpoints (authenticated)
    if (url.pathname === "/api/miniapp/notifications") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      // Verify authentication
      const auth = await requireFlexibleAuth(request, env);
      if (!auth.authenticated) {
        return new Response(auth.error || "Unauthorized", { status: 401 });
      }

      // GET /api/miniapp/notifications - Check if user has notifications enabled
      if (request.method === "GET") {
        try {
          const key = `notifications_enabled:${auth.fid}`;
          const value = await env.KV_USER_PROFILES.get(key);
          const notificationsEnabled = value === 'true';

          return Response.json({ notificationsEnabled });
        } catch (error) {
          console.error("Error checking notification status:", error);
          return new Response("Internal Server Error", { status: 500 });
        }
      }

      // POST /api/miniapp/notifications - Update notification enabled/disabled status
      if (request.method === "POST") {
        try {
          const body = await request.json();
          const { enabled } = body as { enabled: boolean };

          const key = `notifications_enabled:${auth.fid}`;
          await env.KV_USER_PROFILES.put(key, enabled ? 'true' : 'false');

          console.log(`Marked notifications as ${enabled ? 'enabled' : 'disabled'} for FID ${auth.fid}`);

          return Response.json({ success: true, notificationsEnabled: enabled });
        } catch (error) {
          console.error("Error updating notification status:", error);
          return new Response("Internal Server Error", { status: 500 });
        }
      }

      return new Response("Method Not Allowed", { status: 405 });
    }

    // User Points endpoints (authenticated)
    if (url.pathname === "/api/points" && request.method === "GET") {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      // Verify authentication
      const auth = await requireFlexibleAuth(request, env);
      if (!auth.authenticated) {
        return new Response(auth.error || "Unauthorized", { status: 401 });
      }

      try {
        const pointsService = PointsService.fromEnv(env);
        const points = await pointsService.getPoints(auth.fid);

        return Response.json(points);
      } catch (error) {
        console.error("Error fetching points:", error);
        return new Response("Internal Server Error", { status: 500 });
      }
    }

    // User Settings endpoints (authenticated)
    if (url.pathname.startsWith("/api/settings")) {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      // Verify authentication
      const auth = await requireFlexibleAuth(request, env);
      if (!auth.authenticated) {
        return new Response(auth.error || "Unauthorized", { status: 401 });
      }

      const settingsService = UserSettingsService.fromEnv(env);

      // GET /api/settings - Get current user's settings
      if (url.pathname === "/api/settings" && request.method === "GET") {
        try {
          const settings = await settingsService.getSettings(auth.fid);
          return Response.json(settings);
        } catch (error) {
          console.error("Error fetching settings:", error);
          return new Response("Internal Server Error", { status: 500 });
        }
      }

      // PATCH /api/settings - Update current user's settings
      if (url.pathname === "/api/settings" && request.method === "PATCH") {
        try {
          const updates = await request.json();
          const settings = await settingsService.updateSettings(auth.fid, updates);
          return Response.json(settings);
        } catch (error) {
          console.error("Error updating settings:", error);
          return new Response("Internal Server Error", { status: 500 });
        }
      }

      // DELETE /api/settings - Reset current user's settings to defaults
      if (url.pathname === "/api/settings" && request.method === "DELETE") {
        try {
          const settings = await settingsService.resetSettings(auth.fid);
          return Response.json(settings);
        } catch (error) {
          console.error("Error resetting settings:", error);
          return new Response("Internal Server Error", { status: 500 });
        }
      }
    }

    // Queries endpoints
    if (url.pathname.startsWith("/api/queries")) {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);

      // GET /api/queries/:id/answers - List answers for a query (public endpoint)
      const answersMatch = url.pathname.match(/^\/api\/queries\/([a-zA-Z0-9-]+)\/answers$/);
      if (answersMatch && request.method === "GET") {
        const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min for reads
        if (!allowed) return new Response("Too Many Requests", { status: 429 });
        return handleListAnswers(request, env, answersMatch[1]);
      }

      // GET /api/queries/:id - Get a single query
      const idMatch = url.pathname.match(/^\/api\/queries\/([a-zA-Z0-9-]+)$/);
      if (idMatch && request.method === "GET") {
        const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min for reads
        if (!allowed) return new Response("Too Many Requests", { status: 429 });
        return handleGetQuery(request, env, idMatch[1]);
      }

      // GET /api/queries - List all queries
      if (url.pathname === "/api/queries" && request.method === "GET") {
        const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min for reads
        if (!allowed) return new Response("Too Many Requests", { status: 429 });
        return handleListQueries(request, env);
      }

      // POST /api/queries/:id/sync-counts - Sync pub_answers and priv_answers from actual counts
      // Includes: Public answers, Anon answers, and Farcaster replies
      const syncMatch = url.pathname.match(/^\/api\/queries\/([a-zA-Z0-9-]+)\/sync-counts$/);
      if (syncMatch && request.method === "POST") {
        const allowed = await rateLimitService.checkLimit(ip, 10, 60); // 10 req/min for writes
        if (!allowed) return new Response("Too Many Requests", { status: 429 });
        
        const queryId = syncMatch[1];
        
        try {
          // Get query with cast_hash
          const query = await env.DB.prepare(`
            SELECT q.id, fc.cast_hash 
            FROM queries q
            LEFT JOIN farcaster_casts fc ON fc.entity_type = 'query' AND fc.entity_id = q.id
            WHERE q.id = ?
          `).bind(queryId).first() as { id: string; cast_hash?: string } | null;
          
          if (!query) {
            return new Response('Query not found', { status: 404 });
          }
          
          // Count public + anon answers from D1 (D1 only stores Public and Anon, not Private/Allowlist)
          const d1CountResult = await env.DB.prepare(
            "SELECT COUNT(*) as count FROM Answers WHERE q_id = ?"
          ).bind(queryId).first() as { count: number } | null;
          const d1AnswerCount = d1CountResult?.count || 0;
          
          // Count Farcaster replies if cast_hash exists
          let farcasterRepliesCount = 0;
          if (query.cast_hash) {
            try {
              const signerService = createSignerService(env.NEYNAR_API_KEY);
              const conversation = await signerService.getCastConversation(query.cast_hash);
              
              // If null, cast was deleted - clear the cast_hash from farcaster_casts
              if (conversation === null) {
                console.log(`[Farcaster Stats] Cast ${query.cast_hash} deleted, clearing from DB`);
                await env.DB.prepare(
                  "DELETE FROM farcaster_casts WHERE cast_hash = ?"
                ).bind(query.cast_hash).run();
                // Also clear from queries table if stored there
                await env.DB.prepare(
                  "UPDATE Queries SET cast_hash = NULL WHERE cast_hash = ?"
                ).bind(query.cast_hash).run();
              } else {
                // Use the parent cast's reply count from Farcaster
                farcasterRepliesCount = conversation.cast.replies?.count || 0;
              }
            } catch (neynarError) {
              console.error('Error fetching Farcaster replies count:', neynarError);
              // Continue without Farcaster replies if API fails
            }
          }
          
          // Total public-facing answers (D1 answers + Farcaster replies)
          const totalPubAnswers = d1AnswerCount + farcasterRepliesCount;
          
          // Count private/allowlist answers from Nillion
          let privCount = 0;
          try {
            const { NillionProxyClient } = await import('./services/NillionProxyClient');
            const nillionClient = new NillionProxyClient(
              env.NILLION_PROXY_URL,
              env.NILLION_PROXY_SECRET
            );
            
            // Get private answers count
            const privateResult = await nillionClient.listAnswers(queryId, undefined, 'Private');
            privCount = privateResult.total || 0;
            
            // Also count allowlist answers as private
            const allowlistResult = await nillionClient.listAnswers(queryId, undefined, 'Allowlist');
            privCount += allowlistResult.total || 0;
          } catch (nillionError) {
            console.error('Error fetching Nillion answer counts:', nillionError);
            // Continue with 0 priv count if Nillion fails
          }
          
          // Update the queries table
          await env.DB.prepare(
            'UPDATE queries SET pub_answers = ?, priv_answers = ? WHERE id = ?'
          ).bind(totalPubAnswers, privCount, queryId).run();
          
          return Response.json({
            success: true,
            queryId,
            pub_answers: totalPubAnswers,
            priv_answers: privCount,
            details: {
              d1_answers: d1AnswerCount,
              farcaster_replies: farcasterRepliesCount,
              private: privCount
            }
          });
        } catch (error) {
          console.error('Error syncing answer counts:', error);
          return new Response('Failed to sync answer counts', { status: 500 });
        }
      }

      // POST /api/queries - Create a new query (requires auth)
      if (url.pathname === "/api/queries" && request.method === "POST") {
        const allowed = await rateLimitService.checkLimit(ip, 10, 60); // 10 req/min for writes
        if (!allowed) return new Response("Too Many Requests", { status: 429 });

        // Verify authentication
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated) {
          return new Response(auth.error || "Unauthorized", { status: 401 });
        }

        try {
          const body = await request.json() as Omit<QuerySubmission, 'coiner_id' | 'coiner_fid' | 'coiner_fname'>;

          // Ensure user exists in DB (auto-create if needed)
          const userRow = await ensureUserExists(env, auth.fid);

          if (!userRow) {
            return new Response('Failed to create/retrieve user', { status: 500 });
          }

          // Inject authenticated user data into the request body
          // This prevents client manipulation of user identity
          const verifiedBody = {
            ...body,
            coiner_id: userRow.id,      // Internal DB ID
            coiner_fid: auth.fid,       // FID from JWT
            coiner_fname: userRow.fname // Username from DB
          };

          // Add verified FID to headers for the handler
          const headers = new Headers(request.headers);
          headers.set('X-Verified-FID', auth.fid.toString());

          const verifiedRequest = new Request(request.url, {
            method: request.method,
            headers: headers,
            body: JSON.stringify(verifiedBody)
          });

          return handleCreateQuery(verifiedRequest, env);
        } catch (e) {
          console.error('Error validating query request:', e);
          return new Response('Invalid request', { status: 400 });
        }
      }
    }

    // Answer endpoints
    if (url.pathname.startsWith("/api/answers")) {
      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);

      // GET /api/answers/:id - Get a single answer (public for Public audience, auth required for others)
      const answerIdMatch = url.pathname.match(/^\/api\/answers\/([a-zA-Z0-9-]+)$/);
      if (answerIdMatch && request.method === "GET") {
        const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min for reads
        if (!allowed) return new Response("Too Many Requests", { status: 429 });
        return handleGetAnswer(request, env, answerIdMatch[1]);
      }

      // PUT /api/answers/:id - Update an identity answer (requires auth)
      if (answerIdMatch && request.method === "PUT") {
        const allowed = await rateLimitService.checkLimit(ip, 10, 60); // 10 req/min
        if (!allowed) return new Response("Too Many Requests", { status: 429 });

        // Verify authentication
        const auth = await requireFlexibleAuth(request, env);
        if (!auth.authenticated) {
          return new Response(auth.error || "Unauthorized", { status: 401 });
        }

        return handleUpdateAnswer(request, env, answerIdMatch[1]);
      }
    }

    // GET /api/users/:fid/answers - Get user's existing answer(s) for a specific question
    if (url.pathname.match(/^\/api\/users\/\d+\/answers$/) && request.method === "GET") {
      const fidMatch = url.pathname.match(/^\/api\/users\/(\d+)\/answers$/);
      if (fidMatch) {
        const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
        const rateLimitService = RateLimitService.fromEnv(env);
        const allowed = await rateLimitService.checkLimit(ip, 60, 60); // 60 req/min
        if (!allowed) return new Response("Too Many Requests", { status: 429 });

        return handleGetUserAnswers(request, env, fidMatch[1]);
      }
    }

    // POST /api/test/taxonomy-classification/single - Test single question with latency
    if (url.pathname === "/api/test/taxonomy-classification/single" && request.method === "POST") {
      // Only allow on dev domain
      if (!isDevDomain(request)) {
        return new Response("Not Found", { status: 404 });
      }

      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 30, 60); // 30 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      try {
        const { stem, options } = await request.json() as { stem: string; options?: string[] };

        if (!stem) {
          return Response.json({ error: 'stem is required' }, { status: 400 });
        }

        const aiService = AIService.fromEnv(env);
        const startTime = Date.now();
        const result = await aiService.classifyQuestion(stem, options);
        const endTime = Date.now();
        const latencyMs = endTime - startTime;

        return Response.json({
          result,
          latency: {
            ms: latencyMs,
            seconds: (latencyMs / 1000).toFixed(2)
          }
        });
      } catch (error) {
        console.error("Error classifying single question:", error);
        return Response.json(
          { error: 'Failed to classify question', details: String(error) },
          { status: 500 }
        );
      }
    }

    // POST /api/test/taxonomy-classification - Run taxonomy classification tests
    if (url.pathname === "/api/test/taxonomy-classification" && request.method === "POST") {
      // Only allow on dev domain
      if (!isDevDomain(request)) {
        return new Response("Not Found", { status: 404 });
      }

      const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
      const rateLimitService = RateLimitService.fromEnv(env);
      const allowed = await rateLimitService.checkLimit(ip, 20, 60); // 20 req/min
      if (!allowed) {
        return new Response("Too Many Requests", { status: 429 });
      }

      try {
        const aiService = AIService.fromEnv(env);

        // Test cases from test-taxonomy-classification.ts
        const testCases = [
          {
            name: "Identity + Complete + Preference + Low",
            stem: "What's your favorite color?",
            options: undefined,
            expected: {
              primary_type: 'identity',
              construction_type: 'complete',
              content_tags: ['preference'],
              sensitivity: 'low',
            }
          },
          {
            name: "Recurring + Complete + Emotional + Medium",
            stem: "How do you feel today?",
            options: undefined,
            expected: {
              primary_type: 'recurring',
              construction_type: 'complete',
              content_tags: ['emotional'],
              sensitivity: 'medium',
              temporal_markers: ['today']
            }
          },
          {
            name: "Prospective + Complete + Behavioral + Medium",
            stem: "What are your plans for 2026?",
            options: undefined,
            expected: {
              primary_type: 'prospective',
              construction_type: 'complete',
              content_tags: ['behavioral'],
              sensitivity: 'medium',
            }
          },
          {
            name: "Identity + Template + Preference + Low",
            stem: "Would you rather:",
            options: ["be rich", "be famous"],
            expected: {
              primary_type: 'identity',
              construction_type: 'template',
              content_tags: ['preference'],
              sensitivity: 'low',
              is_template: true
            }
          },
          {
            name: "Recurring + Template + Preference + Low",
            stem: "Right now, would you prefer:",
            options: ["coffee", "tea"],
            expected: {
              primary_type: 'recurring',
              construction_type: 'template',
              content_tags: ['preference'],
              sensitivity: 'low',
              is_template: true,
              temporal_markers: ['right now']
            }
          },
          {
            name: "Prospective + Complete + Belief + High",
            stem: "How do you think you'll vote in the next election?",
            options: undefined,
            expected: {
              primary_type: 'prospective',
              construction_type: 'complete',
              content_tags: ['belief'],
              sensitivity: 'high',
            }
          },
          {
            name: "Identity + Complete + Belief + High",
            stem: "What is your religious or spiritual orientation?",
            options: undefined,
            expected: {
              primary_type: 'identity',
              construction_type: 'complete',
              content_tags: ['belief'],
              sensitivity: 'high',
            }
          },
          {
            name: "Recurring + Complete + Behavioral + Medium",
            stem: "What's your current stress level?",
            options: undefined,
            expected: {
              primary_type: 'recurring',
              construction_type: 'complete',
              content_tags: ['emotional'],
              sensitivity: 'medium',
              temporal_markers: ['current']
            }
          },
          {
            name: "Prospective + Complete + Demographic + Medium",
            stem: "What career will you be in 5 years from now?",
            options: undefined,
            expected: {
              primary_type: 'prospective',
              construction_type: 'complete',
              content_tags: ['demographic'],
              sensitivity: 'medium',
            }
          },
          {
            name: "Identity + Template + Preference + Low (colon detection)",
            stem: "This or that:",
            options: ["cats", "dogs"],
            expected: {
              primary_type: 'identity',
              construction_type: 'template',
              content_tags: ['preference'],
              sensitivity: 'low',
              is_template: true
            }
          },
          {
            name: "Past Question: Specific Historical Event",
            stem: "How did you feel during the COVID-19 lockdown in 2020?",
            options: undefined,
            expected: {
              primary_type: 'identity', // Past memory, not tracking
              construction_type: 'complete',
              content_tags: ['behavioral'],
              sensitivity: 'medium',
            }
          },
          {
            name: "Past Question: Childhood Identity",
            stem: "What were you like as a teenager?",
            options: undefined,
            expected: {
              primary_type: 'identity', // Past self is part of identity
              construction_type: 'complete',
              content_tags: ['behavioral'],
              sensitivity: 'low',
            }
          },
          {
            name: "Past Question: Historical Belief",
            stem: "What was your worldview in 2016?",
            options: undefined,
            expected: {
              primary_type: 'identity', // Fixed past memory
              construction_type: 'complete',
              content_tags: ['belief'],
              sensitivity: 'medium',
            }
          },
          {
            name: "Knowledge + Advice + Complete",
            stem: "What's the best way to learn Rust?",
            options: undefined,
            expected: {
              primary_type: 'knowledge',
              knowledge_subtype: 'advice',
              construction_type: 'complete',
              content_tags: [], // Knowledge questions have no content_tags
              sensitivity: 'low',
            }
          },
          {
            name: "Knowledge + Problem + Complete",
            stem: "What are the most interesting open questions in science?",
            options: undefined,
            expected: {
              primary_type: 'knowledge',
              knowledge_subtype: 'problem',
              construction_type: 'complete',
              content_tags: [], // Knowledge questions have no content_tags
              sensitivity: 'low',
            }
          },
          {
            name: "Knowledge + Factual + Complete",
            stem: "How does TCP/IP work?",
            options: undefined,
            expected: {
              primary_type: 'knowledge',
              knowledge_subtype: 'factual',
              construction_type: 'complete',
              content_tags: [],
              sensitivity: 'low',
            }
          },
          {
            name: "Knowledge + Discussion + Complete",
            stem: "Is Rust worth learning in 2026?",
            options: undefined,
            expected: {
              primary_type: 'knowledge',
              knowledge_subtype: 'discussion',
              construction_type: 'complete',
              content_tags: [],
              sensitivity: 'low',
            }
          },
          {
            name: "Identity vs Knowledge: YOUR experience",
            stem: "How did YOU learn to code?",
            options: undefined,
            expected: {
              primary_type: 'identity', // About YOUR personal experience
              construction_type: 'complete',
              content_tags: ['behavioral'],
              sensitivity: 'low',
            }
          },
          // Prediction test cases
          {
            name: "Knowledge + Prediction: AI sentience",
            stem: "Will AI become sentient by 2030?",
            options: undefined,
            expected: {
              primary_type: 'knowledge',
              knowledge_subtype: 'prediction',
              construction_type: 'complete',
              content_tags: [],
              sensitivity: 'medium',
            }
          },
          {
            name: "Knowledge + Prediction: Election",
            stem: "Who will win the 2028 US presidential election?",
            options: undefined,
            expected: {
              primary_type: 'knowledge',
              knowledge_subtype: 'prediction',
              construction_type: 'complete',
              content_tags: [],
              sensitivity: 'high',
            }
          },
          {
            name: "Knowledge + Prediction: Crypto",
            stem: "What will Bitcoin be worth in 5 years?",
            options: undefined,
            expected: {
              primary_type: 'knowledge',
              knowledge_subtype: 'prediction',
              construction_type: 'complete',
              content_tags: [],
              sensitivity: 'low',
            }
          },
          // Additional random test cases
          {
            name: "Identity + Preference: Food",
            stem: "What's the best pizza topping?",
            options: undefined,
            expected: {
              primary_type: 'identity',
              construction_type: 'complete',
              content_tags: ['preference'],
              sensitivity: 'low',
            }
          },
          {
            name: "Identity + Social: Relationships",
            stem: "What do you value most in a friendship?",
            options: undefined,
            expected: {
              primary_type: 'identity',
              construction_type: 'complete',
              content_tags: ['social', 'preference'],
              sensitivity: 'low',
            }
          },
          {
            name: "Identity + Behavioral: Hobbies",
            stem: "What do you do to relax on weekends?",
            options: undefined,
            expected: {
              primary_type: 'identity',
              construction_type: 'complete',
              content_tags: ['behavioral'],
              sensitivity: 'low',
            }
          },
          {
            name: "Identity + Hypothetical: Philosophical",
            stem: "If you could live in any era of history, which would you choose?",
            options: undefined,
            expected: {
              primary_type: 'identity',
              construction_type: 'complete',
              content_tags: ['hypothetical', 'preference'],
              sensitivity: 'low',
            }
          },
          {
            name: "Knowledge + Evaluative: Entertainment",
            stem: "How would you rate The Last of Us TV show?",
            options: undefined,
            expected: {
              primary_type: 'knowledge',
              knowledge_subtype: 'evaluative',
              construction_type: 'complete',
              content_tags: [],
              sensitivity: 'low',
            }
          }
        ];

        const results = [];

        for (const testCase of testCases) {
          try {
            const result = await aiService.classifyQuestion(testCase.stem, testCase.options);

            // Validate result
            const errors = [];

            if (result.primary_type !== testCase.expected.primary_type) {
              errors.push(`primary_type: expected ${testCase.expected.primary_type}, got ${result.primary_type}`);
            }

            // Check knowledge_subtype if primary_type is knowledge
            if (result.primary_type === 'knowledge' && testCase.expected.knowledge_subtype) {
              if (result.knowledge_subtype !== testCase.expected.knowledge_subtype) {
                errors.push(`knowledge_subtype: expected ${testCase.expected.knowledge_subtype}, got ${result.knowledge_subtype}`);
              }
            }

            if (result.construction_type !== testCase.expected.construction_type) {
              errors.push(`construction_type: expected ${testCase.expected.construction_type}, got ${result.construction_type}`);
            }

            // Sensitivity is informational only, not validated for pass/fail
            // if (result.sensitivity !== testCase.expected.sensitivity) {
            //   errors.push(`sensitivity: expected ${testCase.expected.sensitivity}, got ${result.sensitivity}`);
            // }

            // Check content_tags (at least one expected tag should be present, unless knowledge question)
            if (result.primary_type === 'knowledge') {
              // Knowledge questions should have empty content_tags
              if (result.content_tags.length > 0) {
                errors.push(`content_tags: knowledge questions should have empty content_tags, got [${result.content_tags.join(', ')}]`);
              }
            } else {
              // Identity/recurring/prospective should have at least one expected tag
              const hasExpectedTag = testCase.expected.content_tags.some((tag: string) =>
                result.content_tags.includes(tag as any)
              );
              if (!hasExpectedTag) {
                errors.push(`content_tags: expected one of [${testCase.expected.content_tags.join(', ')}], got [${result.content_tags.join(', ')}]`);
              }
            }

            // Check is_template if specified
            if (testCase.expected.is_template !== undefined && result.is_template !== testCase.expected.is_template) {
              errors.push(`is_template: expected ${testCase.expected.is_template}, got ${result.is_template}`);
            }

            // Temporal markers are informational only, not validated for pass/fail
            // if (testCase.expected.temporal_markers) {
            //   if (!result.temporal_markers || result.temporal_markers.length === 0) {
            //     errors.push(`temporal_markers: expected markers, got none`);
            //   }
            // }

            // For exploratory tests with 'unknown' expected type, don't validate primary_type
            const isExploratory = testCase.expected.primary_type === 'unknown';
            const finalErrors = isExploratory
              ? errors.filter(e => !e.startsWith('primary_type:'))
              : errors;
            results.push({
              name: testCase.name,
              stem: testCase.stem,
              options: testCase.options,
              result,
              expected: testCase.expected,
              passed: finalErrors.length === 0,
              errors: finalErrors
            });
          } catch (error) {
            results.push({
              name: testCase.name,
              stem: testCase.stem,
              options: testCase.options,
              passed: false,
              errors: [String(error)]
            });
          }
        }

        const passed = results.filter(r => r.passed).length;
        const failed = results.filter(r => !r.passed).length;

        return Response.json({
          summary: {
            total: results.length,
            passed,
            failed,
            passRate: (passed / results.length * 100).toFixed(1)
          },
          results
        });
      } catch (error) {
        console.error("Error running taxonomy classification tests:", error);
        return new Response("Internal Server Error", { status: 500 });
      }
    }

    // Neynar Webhook for Miniapp Events
    if (url.pathname === "/webhooks/neynar" && request.method === "POST") {
      try {
        const event = await request.json() as {
          type: 'miniapp.add' | 'miniapp.remove' | 'notifications.enabled' | 'notifications.disabled';
          fid: number;
          timestamp: string;
          notification_details?: {
            url: string;
            token: string;
          };
        };

        console.log(`[Webhook] Received ${event.type} event for FID ${event.fid}`);

        // Update miniapp status in KV based on event type
        const key = `miniapp_added:${event.fid}`;

        switch (event.type) {
          case 'miniapp.add':
            await env.KV_USER_PROFILES.put(key, 'true');
            console.log(`[Webhook] Miniapp added by FID ${event.fid}`);
            break;

          case 'miniapp.remove':
            await env.KV_USER_PROFILES.put(key, 'false');
            console.log(`[Webhook] Miniapp removed by FID ${event.fid}`);
            break;

          case 'notifications.enabled':
            // Store notification enabled status
            const notifKey = `notifications_enabled:${event.fid}`;
            await env.KV_USER_PROFILES.put(notifKey, 'true');
            console.log(`[Webhook] Notifications enabled by FID ${event.fid}`);
            break;

          case 'notifications.disabled':
            // Store notification disabled status
            const notifDisabledKey = `notifications_enabled:${event.fid}`;
            await env.KV_USER_PROFILES.put(notifDisabledKey, 'false');
            console.log(`[Webhook] Notifications disabled by FID ${event.fid}`);
            break;
        }

        return Response.json({ success: true });
      } catch (error) {
        console.error('[Webhook] Error processing Neynar webhook:', error);
        return new Response("Internal Server Error", { status: 500 });
      }
    }

    if (url.pathname.startsWith("/api/")) {
      return Response.json({
        name: "Cloudflare",
      });
    }

    // Try to fetch the asset first
    const assetResponse = await env.ASSETS.fetch(request);

    // If asset found (200), return it
    if (assetResponse.status === 200) {
      return assetResponse;
    }

    // If asset not found (404), serve index.html for SPA routing
    // This handles all client-side routes like /questions, /profile/*, etc.
    const indexRequest = new Request(new URL('/index.html', url.origin), {
      method: 'GET',
      headers: request.headers
    });

    const indexResponse = await env.ASSETS.fetch(indexRequest);

    if (indexResponse.ok) {
      return new Response(indexResponse.body, {
        status: 200,
        headers: {
          'Content-Type': 'text/html;charset=UTF-8',
          'Cache-Control': 'public, max-age=0, must-revalidate'
        }
      });
    }

    // If even index.html is missing, return 404
    return new Response('Not Found', { status: 404 });
  },
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
} as any;
